
--Cooperators
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'12 Kroków',N'/Content/ads/cooperators/12krokow.jpg',N'12 Kroków','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.domowykosciol.org/',N'Domowy Kościół Chicago','/Content/ads/cooperators/domowy_kosciol.jpg',N'Domowy Kościół Chicago','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.jp2group.com/',N'JPII Group','/Content/ads/cooperators/jp2group.jpg',N'JPII Group','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'Krąg Miłosierdzia','/Content/ads/cooperators/krag_milosierdzia.jpg',N'Krąg Miłosierdzia','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'Towarzystwo Przyjaciół i Absolwentów KUL w Chicago','/Content/ads/cooperators/kul_absolwenci.jpg',N'Towarzystwo Przyjaciół i Absolwentów KUL w Chicago','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.familyministries.org/',N'Marriage and Family Ministries','/Content/ads/cooperators/marriage_fam_ministries.jpg',N'Marriage and Family Ministries','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'New Evangelization','/Content/ads/cooperators/new_evangelization.jpg',N'New Evangelization','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'Płomyczek','/Content/ads/cooperators/plomyczek.jpg',N'Płomyczek','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://polski.fm/',N'Polski FM','/Content/ads/cooperators/polski_fm.jpg',N'Polski FM','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.polskieradio.com/',N'Polskie Radio','/Content/ads/cooperators/polskie_radio.png',N'Polskie Radio','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.wpna1490am.com/"',N'WPNA','/Content/ads/cooperators/radio_maryja.jpg',N'WPNA','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.radiosiedem.net/',N'Radio Siedem','/Content/ads/cooperators/radio7.jpg',N'Radio Siedem','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.relevantradio.com/',N'Relevant Radio','/Content/ads/cooperators/relevant_radio.jpg',N'Relevant Radio','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://sychar.org/',N'Sychar','/Content/ads/cooperators/sychar.org.jpg',N'Sychar','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.trojcowo.com/',N'Trójcowo Chicago','/Content/ads/cooperators/trojcowo.jpg',N'Trójcowo Chicago','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://tv-trwam.pl/',N'Trwam','/Content/ads/cooperators/trwam.jpg',N'Trwam','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.wcev1450.com/',N'WCEV 1450 AM','/Content/ads/cooperators/wcev1450.gif',N'WCEV 1450 AM','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.wzch.org.pl/',N'WŻCH','/Content/ads/cooperators/wzch.jpg',N'WŻCH','Cooperator')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.yamchicago.org/',N'Young Adult Ministry','/Content/ads/cooperators/young_adult_ministry.jpg',N'Young Adult Ministry','Cooperator')

--Media Patrons
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://catholicleaguepolonia.org/en/',N'Catholic League','/Content/ads/media_patrons/catholic_league.jpg',N'Catholic League','MediaPatron')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://dziennikzwiazkowy.com/',N'Dziennik Związkowy','/Content/ads/media_patrons/dziennik_zwiazkowy.jpg',N'Dziennik Związkowy','MediaPatron')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.polvision.com/',N'Polvision','/Content/ads/media_patrons/polvision.png',N'Polvision','MediaPatron')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://radiodeon.com/',N'Radio Deon','/Content/ads/media_patrons/radio_deon.jpg',N'Radio Deon','MediaPatron')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.relevantradio.com/',N'Relevant Radio','/Content/ads/media_patrons/relevant_radio.jpg',N'Relevant Radio','MediaPatron')

--Sponsors
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.montrosedeli.com/',N'Montrose Deli','/Content/ads/sponsors/montrose.jpg',N'Montrose Deli','Sponsor')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://www.activeconcept.com/',N'Active Concept, Inc.','/Content/ads/sponsors/active_concept.jpg',N'Active Concept, Inc.','Sponsor')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('http://catholicleaguepolonia.org/en/',N'Catholic League','/Content/ads/sponsors/catholic_league.jpg',N'Catholic League','Sponsor')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'Spine Advanced','/Content/ads/sponsors/spine_advanced.jpg',N'Spine Advanced','Sponsor')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'Wiklanski''s Bakery','/Content/ads/sponsors/wiklanski_bakery.jpg',N'Wiklanski''s Bakery','Sponsor')
INSERT INTO Cooperators(SiteUrl, SiteTitle, LogoPath, ImageAlt, [Type])
VALUES('#',N'Blue Box','/Content/ads/sponsors/blue_box.jpg',N'Blue Box','Sponsor')