INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Mark Nimo', N'St. Daniel The Prophet  located at 5300 S. Natoma Ave., Chicago IL 60638', N'Sunday, February 8th, 4pm - 6pm, Mass at 3 pm prior to the conference.', N'How to survive and benefit from being loved and educated.', N'Young adults', 'English', 10)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Dr. Robert Lawler', N'St. Ferdinand Chapel located at 3131 N. Mason Ave., Chicago IL 60634', N'Sunday, February 8th, 11am - 1pm, Mass at 10am prior to the conference.', N'We are all called to love and educate, myths, lies and truth in today''s sexual education.', N'All', 'English', 20)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Sheila Liaugminas', N'St. Bruno Church located at 4751 South Harding Avenue, Chicago IL 60632', N'Sunday, February 15th, 4pm - 6pm, Mass at 3 pm prior to the conference.', N'', N'All', 'English', 30)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Chuck Thompson', N'St. Bruno Church located at 4751 South Harding Avenue, Chicago IL 60632', N'Sunday, February 15th, homily at the Mass at 3 pm.', N'We are all called to love and educate in the context of religious education.', N'All', 'English', 40)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Raymund Pingoy', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Tuesday, February 10th at 8:45pm.', N'John Paul II - Theology of the body.', N'Young adults', 'English', 50)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'<b>Fr. Marek Dziewiecki</b>', N'<b>Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634</b>', N'<b>Saturday, Februaty 7th at 5pm.</b>', N'<b>Homily at the Mass (5pm) - Congress Opening.</b>', N'All', 'Polish', 60)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Sunday, February 8th at 8am.', N'Homily at the Mass (8am)', N'All', 'Polish', 70)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'St. Gertrude located at 9613 Schiller Boulevard, Franklin Park IL 60131', N'Sunday, February 8th at 10am.', N'Homily at the Mass (10am)', N'All', 'Polish', 80)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'St. Daniel the Prophet located at 5300 S. Natoma Ave., Chicago IL 60638', N'Sunday, February 8th at 1pm.', N'Homily at the Mass (1pm)', N'All', 'Polish', 90)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'St. Bruno Church located at 4751 South Harding Avenue, Chicago IL 60632', N'Sunday, February 8th at 3pm.', N'Homily at the Mass (3pm)', N'All', 'Polish', 100)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Our Lady Mother of the Church Polish Mission located at 116 Hilton St., Willow Spring IL 60480', N'Sunday, February 8th at 6pm.', N'Homily at the Mass (6pm)', N'All', 'Polish', 110)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Monday, February 9th at 7pm.', N'Homily at the Mass (7pm)', N'All', 'Polish', 120)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'St. Constance Church located at 5843 West Strong Street, Chicago IL 60630', N'Tuesday, February 10th at 7pm.', N'Conference.', N'All', 'Polish', 130)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Wednesday, February 11th at 7pm.', N'Homily at the Mass (7pm)', N'All', 'Polish', 140)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Thursday, February 12th at 7pm.', N'Homily at the Mass (7pm)', N'All', 'Polish', 150)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Friday, February 13th at 7pm.', N'Homily at the Mass (7pm)', N'All', 'Polish', 160)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Friday, February 13th at 8:45pm.', N'Conference.', N'Young adults', 'Polish', 170)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Saturday, February 14th at 3pm.', N'Symposium', N'All', 'Polish', 180)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Sunday, February 15th at 8am.', N'Homily at the Mass (8am)', N'All', 'Polish', 190)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marek Dziewiecki', N'St. Thomas Becket Church located at 1321 North Burning Bush Lane, Mount Prospect IL 60056', N'Sunday, February 15th at 10:45am.', N'Homily at the Mass (10:45am)', N'All', 'Polish', 200)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'<b>Fr. Marek Dziewiecki</b>', N'<b>St. Hyacinth Basilica located at 3636 West Wolfram Street, Chicago IL 60618</b>', N'<b>Sunday, February 15th at 3pm.</b>', N'<b>Homily at the Mass (3pm) - Congress Closing.</b>', N'<b>All</b>', 'Polish', 210)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'St. Hyacinth Basilica located at 3636 West Wolfram Street, Chicago IL 60618', N'Monday, February 9th.', N'Conference after the Mass at 7pm.', N'All', 'Polish', 220)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Tuesday, February 10th.', N'Conference after the Mass at 7pm.', N'All', 'Polish', 230)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Tuesday, February 10th at 8:45pm.', N'Conference.', N'Young adults', 'Polish', 240)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'Divine Mercy located at 21W411 Sunset Avenue, Lombard IL 60148', N'Wednesday, February 11th.', N'Conference after the Mass at 7pm.', N'All', 'Polish', 250)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Thursday, February 12th', N'Conference after the Mass at 7pm.', N'All', 'Polish', 260)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'St. Hyacinth Basilica located at 3636 West Wolfram Street, Chicago IL 60618', N'Friday, February 13th.', N'Conference after the Mass at 7pm.', N'All', 'Polish', 270)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Saturday, February 14th at 3pm.', N'Symposium', N'All', 'Polish', 280)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'SS. Cyril and Methodius Parish located at 608 Sobieski Street, Lemont IL 60439', N'Sunday, February 15th.', N'Conference after the Mass at 8:30am.', N'All', 'Polish', 290)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'St. Albert the Great located at 8000 S. Linder Ave, Burbank IL 60459', N'Sunday, February 15th.', N'Conference after the Mass at 10:30am.', N'All', 'Polish', 300)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Jacek Pulikowski', N'St Daniel the Prophet located at 5300 S. Natoma Ave., Chicago IL 60638', N'Sunday, February 15th.', N'Conference after the Mass at 1pm.', N'All', 'Polish', 310)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'Holy Trinity Church located at 118 N. Noble Street, Chicago IL 60642', N'Sunday, February 8th.', N'Homily at the Mass (8am).', N'All', 'Polish', 320)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'Holy Trinity Church located at 118 N. Noble Street, Chicago IL 60642', N'Sunday, February 8th.', N'Homily at the Mass (10:30am).', N'All', 'Polish', 330)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'Holy Trinity Church located at 118 N. Noble Street, Chicago IL 60642', N'Sunday, February 8th.', N'Conference after the Mass (10:30am).', N'All', 'Polish', 340)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'Holy Trinity Church located at 118 N. Noble Street, Chicago IL 60642', N'Sunday, February 8th.', N'Homily at the Mass (1pm).', N'All', 'Polish', 350)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'Holy Trinity Church located at 118 N. Noble Street, Chicago IL 60642', N'Sunday, February 8th.', N'Homily at the Mass (4pm).', N'All', 'Polish', 360)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'Holy Trinity Church located at 118 N. Noble Street, Chicago IL 60642', N'Sunday, February 8th.', N'Homily at the Mass (8pm).', N'All', 'Polish', 370)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Saturday, February 14th at 3pm.', N'Symposium.', N'All', 'Polish', 380)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'St. Ferdinand Church located at 5900 West Barry Ave., Chicago IL 60634', N'Sunday, February 15th at 7am.', N'Homily at the Mass (7am).', N'All', 'Polish', 390)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'St. Ferdinand Church located at 5900 West Barry Ave., Chicago IL 60634', N'Sunday, February 15th at 10:15am.', N'Homily at the Mass (10:15am).', N'All', 'Polish', 400)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'St. Ferdinand Church located at 5900 West Barry Ave., Chicago IL 60634', N'Sunday, February 15th at 3pm.', N'Homily at the Mass (3pm).', N'All', 'Polish', 410)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Marian Pokrywka', N'St. Ferdinand Church located at 5900 West Barry Ave., Chicago IL 60634', N'Sunday, February 15th at 7pm.', N'Homily at the Mass (7pm).', N'All', 'Polish', 420)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Pawel Bandurski', N'St. Ladislaus Church located at 5345 West Roscoe Street, Chicago IL 60641', N'Friday, February 6th at 7pm.', N'Homily at the Mass (7pm).', N'All', 'Polish', 430)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Pawel Bandurski', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Saturday, February 7th', N'Conference after the Mass (5pm).', N'All', 'Polish', 440)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Pawel Bandurski', N'Our Lady Mother of the Church Polish Mission located at 116 Hilton St., Willow Spring IL 60480', N'Saturday, February 7th', N'Homily at the Mass (10pm).', N'All', 'Polish', 450)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Pawel Bandurski', N'St. William Church located 2559 North Sayre Avenue, Chicago IL 60707', N'Sunday, February 8th.', N'Homily at the Mass (7pm).', N'All', 'Polish', 460)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Fr. Pawel Bandurski', N'St. Francis Borgia Church located at 8033 West Addison Street, Chicago IL 60634', N'Sunday, February 8th.', N'Homily at the Mass (7pm).', N'All', 'Polish', 470)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Malgorzata Olczak', N'St. Thomas Becket Church located at 1321 North Burning Bush Lane, Mount Prospect IL 60056', N'Sunday, February 8th.', N'Conference after the Mass (10:45am).', N'All', 'Polish', 480)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Malgorzata Olczak', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Wednesday, February 11th at 8:45pm.', N'Conference.', N'Young adults', 'Polish', 490)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Malgorzata Olczak', N'Shrine Of The Sacred Heart located at 5835 W. Irving Park Rd, Chicago IL 60634', N'Saturday, February 14th at 3pm.', N'Symposium.', N'All', 'Polish', 500)
INSERT INTO [Events](ParticipantName, WhereAt, [When], Topic, Audience, [Language], SortOrder)
VALUES(N'Malgorzata Olczak', N'St. Thomas Becket Church located at 1321 North Burning Bush Lane, Mount Prospect IL 60056', N'Sunday, February 15th.', N'Conference after the Mass (10:45am).', N'All', 'Polish', 510)
