using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SqlFu;
using SqlFu.DDL;

namespace FamilyCongress2015.Models
{
    [Table("Events", AutoGenerated = true, CreationOptions = IfTableExists.Ignore, PrimaryKey = "ID")]
    public class Event
    {
        public int ID { get; set; }

        [ColumnOptions(IsNullable = true, Size = "100")]
        public String ParticipantName { get; set; }

        [ColumnOptions(Size = "300")]
        public String WhereAt { get; set; }

        [ColumnOptions(Size = "300")]
        public String When { get; set; }

        [ColumnOptions(Size = "300")]
        public String Topic { get; set; }

        [ColumnOptions(Size = "100")]
        public String Audience { get; set; }

        [ColumnOptions(Size = "10")]
        public String Language { get; set; }

        public int SortOrder { get; set; }
    }
}