using System;
using SqlFu;
using SqlFu.DDL;

namespace FamilyCongress2015.Models
{
    [Table("Participants", AutoGenerated = true, CreationOptions = IfTableExists.Ignore, PrimaryKey = "ID")]
    public class Participant
    {
        public int ID { get; set; }

        [ColumnOptions(IsNullable = false, Size = "100")]
        public String ParticipantName { get; set; }

        [ColumnOptions(IsNullable = true, Size = "100")]
        public String ParticipantTitle { get; set; }

        [ColumnOptions(IsNullable = false)]
        public String ParticipantBio { get; set; }

        [ColumnOptions(IsNullable = true, Size = "100")]
        public String ImageURL { get; set; }
    }
}